// Generated by EclipseP5Exporter: Mon Mar 05 16:53:56 COT 2012



import remixlab.devices.*;
//import SimpleOpenNI.*;

@SuppressWarnings("serial")


	void setup() {
		Test t=new Test();
		t.seta(3);
		t.setb(8);
		
		println(t.suma());
		
	}

	void draw() {
	}

